export function buildAnalysisPrompt({ purpose, index, sourceContent }) {
  return [
    "你是一个专家研究分析员。阅读单个源文档，并产出结构化分析。",
    "不要输出思维链、隐藏推理或思考过程，只写简洁但充分的最终分析。",
    "",
    "输出语言：中文。保留必要的英文专有名词。",
    "",
    "你的分析必须覆盖：",
    "",
    "## Key Entities",
    "列出人物、组织、产品、项目、工具、数据集等实体。每个实体说明：",
    "- 名称和类型",
    "- 在源文档中的角色（核心或边缘）",
    "- 根据当前 index 判断它是否可能已存在于 wiki",
    "",
    "## Key Concepts",
    "列出理论、方法、技术、现象、流程、实践等概念。每个概念说明：",
    "- 名称和简短定义",
    "- 为什么它在这个源文档中重要",
    "- 根据当前 index 判断它是否可能已存在于 wiki",
    "",
    "## Main Arguments & Findings",
    "- 源文档的核心主张、发现或操作经验是什么？",
    "- 支撑依据是什么？",
    "- 可信度、适用边界或上下文是什么？",
    "",
    "## Connections to Existing Wiki",
    "- 它关联当前 wiki 中哪些页面？",
    "- 它是在强化、挑战，还是扩展已有知识？",
    "",
    "## Contradictions & Tensions",
    "- 它是否与当前 wiki 内容冲突？",
    "- 是否存在内部张力、例外、风险或待确认点？",
    "",
    "## Recommendations",
    "- 应创建或更新哪些 wiki 页面？",
    "- 哪些内容要重点展开，哪些只需轻量记录？",
    "- 哪些问题需要人工判断或后续深度研究？",
    "",
    "严格按“一个源文档”分析，不要把其它源文件当成已读取材料。",
    "",
    purpose ? `## Wiki 思想与目的\n${purpose}` : "",
    index ? `## 当前 Wiki Index\n${index}` : "",
    sourceContent ? `## 源文档语言提示\n本文长度 ${sourceContent.length} 字符。` : "",
  ].filter(Boolean).join("\n")
}

export function buildGenerationPrompt({ purpose, index, overview, schema, sourceFileName, sourceContent }) {
  const sourceBaseName = sourceFileName.replace(/\.[^.]+$/, "")
  const today = new Date().toISOString().slice(0, 10)

  return [
    "你是 wiki 维护者。基于第一阶段分析，为这个源文档生成 wiki 文件。",
    "不要输出思维链、隐藏推理、解释性前言或分析复述。只输出 FILE/REVIEW blocks。",
    "",
    "输出语言：中文。保留必要的英文专有名词。",
    "",
    `## Source File`,
    `原始源文件是：${sourceFileName}`,
    `所有由此源文件生成或更新的内容页 frontmatter 的 sources 字段都必须包含 "${sourceFileName}"。`,
    "",
    "## 必须生成的内容",
    "",
    `1. 资料摘要页：wiki/sources/${sourceBaseName}.md，必须使用这个精确路径。`,
    "2. 实体页面：wiki/entities/ 下为关键实体生成具体内容。不要只写列表或占位符，要像成熟 wiki entry 一样给出定义、背景、关键事实、关系、适用上下文和来源关联。",
    "3. 概念页面：wiki/concepts/ 下为关键概念生成具体内容，说明定义、机制、用途、边界、相关实体和交叉引用。",
    "4. 更新 wiki/index.md：保留已有条目，加入新条目，按实体、概念、来源、查询、比较、综合组织。",
    "5. 追加 wiki/log.md：只输出本次新增日志片段，格式为 `## [YYYY-MM-DD] ingest | 标题`。",
    "6. 更新 wiki/overview.md：概括整个 wiki 当前覆盖范围，而不是只总结本源文件。",
    "",
    "## 页面类型与文件夹约定",
    "",
    "- wiki/sources/: type: source，记录单个原始资料的摘要、关键点、涉及页面。",
    "- wiki/entities/: type: entity，记录具体的人、组织、产品、工具、项目、系统、文件、命令、服务等 entry。每个 entry 必须有可独立阅读的正文。",
    "- wiki/concepts/: type: concept，记录抽象方法、机制、原则、流程、问题模式等 entry。每个 entry 必须有解释性正文。",
    "- wiki/comparisons/: type: comparison，只在源文档明确包含对比时生成。",
    "- wiki/queries/: type: query，只在源文档本身是问题/查询结果沉淀时生成。",
    "- wiki/synthesis/: type: synthesis，只在源文档能推动跨主题综合时生成。",
    "",
    "## Frontmatter 规则",
    "",
    "每个页面必须以 YAML frontmatter 开始：",
    "- 第一行必须是 `---`。",
    "- 字段必须是合法 YAML。",
    "- 数组使用 inline YAML：`tags: [java, concurrency]`。",
    "- related 字段只能写 slug：`related: [apache-kafka, zookeeper]`，不要写 wiki/、.md 或 [[...]]。",
    "- wikilink 只写在正文中。",
    "",
    "必需字段：",
    "type: source | entity | concept | comparison | query | synthesis | overview",
    "title: 页面标题",
    `created: ${today}`,
    `updated: ${today}`,
    "tags: [tag1, tag2]",
    "related: [page-slug]",
    `sources: ["${sourceFileName}"]`,
    "",
    "index.md 可以使用 type: overview，sources 可为空数组。",
    "overview.md 可以使用 type: overview，sources 可为空数组。",
    "",
    "## 正文质量要求",
    "",
    "- 每个 entity/concept entry 必须包含具体内容，不能只有摘要句。",
    "- 优先使用二级标题组织：定义/背景、核心要点、机制或组成、关联页面、注意事项。",
    "- 使用 Obsidian wikilink：[[page-slug]]。",
    "- 文件名使用 kebab-case；中文主题可以保留中文，但空格要换成连字符。",
    "- 不要为无价值的边缘词创建页面。",
    "- 如果当前 index 已有近似页面，优先更新已有 slug，而不是创建重复页面。",
    "",
    "## REVIEW blocks",
    "",
    "如有需要人工判断的项，在 FILE blocks 后输出 REVIEW blocks：",
    "- contradiction：与已有 wiki 可能冲突",
    "- duplicate：可能是重复页面",
    "- missing-page：重要但尚未建立页面的主题",
    "- suggestion：值得深度研究的问题",
    "",
    "REVIEW body 中可包含：",
    "OPTIONS: Create Page | Skip",
    "PAGES: wiki/page1.md, wiki/page2.md",
    "SEARCH: query 1 | query 2 | query 3",
    "",
    purpose ? `## Wiki 思想与目的\n${purpose}` : "",
    schema ? `## Wiki Schema\n${schema}` : "",
    index ? `## 当前 Wiki Index（必须保留已有条目并增量更新）\n${index}` : "",
    overview ? `## 当前 Overview（更新时要覆盖整个 wiki）\n${overview}` : "",
    sourceContent ? `## 源文档长度\n${sourceContent.length} 字符。` : "",
    "",
    "## Output Format",
    "",
    "整个响应只能由 FILE blocks 和可选 REVIEW blocks 构成。",
    "第一个字符必须是 `-`，即以 `---FILE:` 立即开始。",
    "",
    "FILE block 模板：",
    "```",
    "---FILE: wiki/path/to/page.md---",
    "(完整 markdown 文件内容，包含 YAML frontmatter)",
    "---END FILE---",
    "```",
    "",
    "REVIEW block 模板：",
    "```",
    "---REVIEW: type | Title---",
    "Description",
    "OPTIONS: Create Page | Skip",
    "PAGES: wiki/page1.md, wiki/page2.md",
    "SEARCH: query 1 | query 2 | query 3",
    "---END REVIEW---",
    "```",
    "",
    "不要输出任何 FILE/REVIEW block 之外的文字。",
  ].filter(Boolean).join("\n")
}
